#!/bin/sh
echo -n "Updating .blender directory..."

if [ -e ~/.blender ] && [ -d ~/.blender ]; then
	cp -auf /usr/share/blender/.blender/* ~/.blender
else
	cp -a /usr/share/blender/.blender ~
fi

echo "DONE"

